pub fn role_name(id: u32) -> String {
    // Canonical ATSPI role enum (at-spi2-core atspi-enum.h)
    match id {
        0 => "invalid",
        1 => "accelerator_label",
        2 => "alert",
        3 => "animation",
        4 => "arrow",
        5 => "calendar",
        6 => "canvas",
        7 => "check_box",
        8 => "check_menu_item",
        9 => "color_chooser",
        10 => "column_header",
        11 => "combo_box",
        12 => "date_editor",
        13 => "desktop_icon",
        14 => "desktop_frame",
        15 => "dial",
        16 => "dialog",
        17 => "directory_pane",
        18 => "drawing_area",
        19 => "file_chooser",
        20 => "filler",
        21 => "focus_traversable",
        22 => "font_chooser",
        23 => "frame",
        24 => "glass_pane",
        25 => "html_container",
        26 => "icon",
        27 => "image",
        28 => "internal_frame",
        29 => "label",
        30 => "layered_pane",
        31 => "list",
        32 => "list_item",
        33 => "menu",
        34 => "menu_bar",
        35 => "menu_item",
        36 => "option_pane",
        37 => "page_tab",
        38 => "page_tab_list",
        39 => "panel",
        40 => "password_text",
        41 => "popup_menu",
        42 => "progress_bar",
        43 => "push_button",
        44 => "radio_button",
        45 => "radio_menu_item",
        46 => "root_pane",
        47 => "row_header",
        48 => "scroll_bar",
        49 => "scroll_pane",
        50 => "separator",
        51 => "slider",
        52 => "spin_button",
        53 => "split_pane",
        54 => "status_bar",
        55 => "table",
        56 => "table_cell",
        57 => "table_column_header",
        58 => "table_row_header",
        59 => "tearoff_menu_item",
        60 => "terminal",
        61 => "text",
        62 => "toggle_button",
        63 => "tool_bar",
        64 => "tool_tip",
        65 => "tree",
        66 => "tree_table",
        67 => "unknown",
        68 => "viewport",
        69 => "window",
        71 => "header",
        72 => "footer",
        73 => "paragraph",
        74 => "ruler",
        75 => "application",
        76 => "autocomplete",
        77 => "editbar",
        78 => "embedded",
        79 => "entry",
        80 => "chart",
        81 => "caption",
        82 => "document_frame",
        83 => "heading",
        84 => "page",
        85 => "section",
        86 => "redundant_object",
        87 => "form",
        88 => "link",
        89 => "input_method_window",
        90 => "table_row",
        91 => "tree_item",
        92 => "document_spreadsheet",
        93 => "document_presentation",
        94 => "document_text",
        95 => "document_web",
        96 => "document_email",
        97 => "comment",
        98 => "list_box",
        99 => "grouping",
        100 => "image_map",
        101 => "notification",
        102 => "info_bar",
        103 => "level_bar",
        104 => "title_bar",
        105 => "block_quote",
        106 => "audio",
        107 => "video",
        108 => "definition",
        109 => "article",
        110 => "landmark",
        111 => "log",
        112 => "marquee",
        113 => "math",
        114 => "rating",
        115 => "timer",
        116 => "static",
        _ => "unknown",
    }
    .into()
}

pub fn parse_states(bits: &[u32]) -> Vec<String> {
    let names = [
        "active",
        "armed",
        "busy",
        "checked",
        "collapsed",
        "defunct",
        "editable",
        "enabled",
        "expandable",
        "expanded",
        "focusable",
        "focused",
        "has_tooltip",
        "horizontal",
        "iconified",
        "modal",
        "multi_line",
        "multiselectable",
        "opaque",
        "pressed",
        "resizable",
        "selectable",
        "selected",
        "sensitive",
        "showing",
        "single_line",
        "stale",
        "transient",
        "vertical",
        "visible",
        "manages_descendants",
        "indeterminate",
        "required",
        "truncated",
        "animated",
        "invalid_entry",
        "supports_autocompletion",
        "selectable_text",
        "is_default",
        "visited",
        "checkable",
        "has_popup",
        "read_only",
    ];
    let mut states = Vec::new();
    for (i, name) in names.iter().enumerate() {
        let word = i / 32;
        let bit = i % 32;
        if let Some(mask) = bits.get(word)
            && mask & (1u32 << bit) != 0
        {
            states.push((*name).to_string());
        }
    }
    states
}
